name: patch-to-live
run-name: Build and deploy headless server
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export game using Godot Export Action
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./fiber
          archive_output: true
          cache: true

      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          scp ${{ steps.export.outputs.archive_directory }}/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/fiber/
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            pkill -i -f fiber_server.x86_64 || true &&
            cd /root/fiber &&
            unzip -o *.zip &&
            rm -f *.zip &&
            chmod +x fiber_server.x86_64 &&
            nohup ./fiber_server.x86_64 --headless > server.log 2>&1 &
          "
