name: patch-to-live
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Godot Headless + Export Templates
        run: |
          GODOT_VERSION=4.3
          # Download Godot headless binary
          wget https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          unzip Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          mv Godot_v${GODOT_VERSION}-stable_linux.x86_64 godot
          chmod +x godot
          
          # Download export templates
          wget https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

          # Verify templates exist
          ls -lh ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Verify project files
        run: |
          ls -lh project.godot
          ls -lh export_presets.cfg

      - name: Export Linux Headless build
        run: |
          ./godot --headless --path . --export-release "Linux/X11 Headless (Runnable)"
          ls -lh ../fiber_server.x86_64*

      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          scp ../fiber_server.x86_64* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/fiber/
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            pkill -i -f fiber_server.x86_64 || true &&
            cd /root/fiber &&
            chmod +x fiber_server.x86_64 &&
            nohup ./fiber_server.x86_64 --headless > server.log 2>&1 &
          "
